- name: Add grafana signing key
  apt_key:
    url: https://packages.grafana.com/gpg.key
    state: present
- name: Include grafana repository
  apt_repository:
    repo: 'deb https://packages.grafana.com/oss/deb stable main'
    state: present
- name: Install grafana
  apt:
    update_cache: true
    name: grafana
    state: latest

- name: Start grafana
  service:
    name: grafana-server
    state: restarted

- name: Set grafana configuration
  template:
    src: templates/grafana.ini.j2
    dest: /etc/grafana/grafana.ini
  notify:
    - Restart grafana

- name: Create influxdb datasource
  grafana_datasource:
    name: "datasource-influxdb"
    grafana_url: "https://{{ ansible_host }}/grafana"
    grafana_user: "admin"
    grafana_password: "{{ grafana.password.admin }}"
    org_id: "1"
    ds_type: "influxdb"
    url: "http://localhost:8086"
    database: "fieldtracks"
    time_interval: ">5s"
    user: "grafana"
    password: "{{ influxdb.password.grafana }}"
    is_default: true

- name: Copy dashboards to remote host
  copy:
    src: "{{ item }}"
    dest: "/tmp/{{ item }}"
    owner: root
    group: root
    mode: '0644'
  with_items:
    - stones.json
    - status.json

- name: Import stones dashboard
  grafana_dashboard:
    grafana_url: "https://{{ ansible_host }}/grafana"
    grafana_user: "admin"
    grafana_password: "{{ grafana.password.admin }}"
    state: present
    message: Updated by ansible
    overwrite: yes
    path: /tmp/stones.json
    uid: stones

- name: Import mqtt-status dashboard
  grafana_dashboard:
    grafana_url: "https://{{ ansible_host }}/grafana"
    grafana_user: "admin"
    grafana_password: "{{ grafana.password.admin }}"
    state: present
    message: Updated by ansible
    overwrite: yes
    path: /tmp/status.json
    uid: status


#- name: Create influxdb datasource
#  grafana_datasource:
#    name: "datasource-influxdb"
#    grafana_url: "http://localhost:3000"
#    grafana_user: "admin"
#    grafana_password: "{{ grafana.password.admin }}"
#    org_id: "1"
#    ds_type: "influxdb"
#    url: "http://localhost:8086"
#    database: "fieldtracks"
#    time_interval: ">10s"
#  notify:
#    - Restart grafana
