- name: Install influxdb
  apt:
    name:
    - influxdb
    #- influxdb-client
    #- python-requests
    - python-influxdb


# The order here matters
- name: Start influxdb
  service:
    name: influxdb
    state: restarted

- name: Create database fieldtracks
  influxdb_database:
    database_name: "fieldtracks"
    username: admin
    password: '{{ influxdb.password.admin  }}'


- name: Create user admin
  influxdb_user:
    user_name: admin
    admin: true
    user_password: '{{ influxdb.password.admin  }}'
    username: admin
    password: '{{ influxdb.password.admin  }}'
  notify:
    - Restart InfluxDB

- name: Create user telegraf
  influxdb_user:
    user_name: telegraf
    admin: true
    user_password: '{{ influxdb.password.telegraf  }}'
    username: admin
    password: '{{ influxdb.password.admin  }}'
  notify:
    - Restart InfluxDB

- name: Create user grafana
  influxdb_user:
    user_name: grafana
    admin: false
    user_password: '{{ influxdb.password.grafana  }}'
    username: admin
    password: '{{ influxdb.password.admin  }}'
    grants:
    - database: 'fieldtracks'
      privilege: 'READ'
  notify:
    - Restart InfluxDB

- name: Create InfluxDB configuration
  template:
    src: influxdb.conf.j2
    dest: /etc/influxdb/influxdb.conf





#- name: Create fieldtracks user
#  influxdb_user:
#    user_name: fieldtracks
#    user_password: '{{ influxdb.password.fieldtracks  }}'
#
#- name: Create fieldtracks database
#  influxdb_user:
#    user_name: fieldtracks
#    user_password: '{{ influxdb.password.fieldtracks  }}'


- import_tasks: grafana.yml
