---
- name: install nginx, openssl, git
  apt:
    state: present
    update_cache: yes
    name:
    - nginx
    - curl
    - git
    - openssl
- include: dehydrated.yml
- include: nginx-tls.yml

- name: Copy webdav password file /etc/nginx/webdav.passwd
  copy: >
    src={{ item }}
    dest=/etc/nginx/{{ item }}
    mode='0640'
    owner=root
    group=www-data
  with_items:
  - webdav.passwd
  - firmware.passwd

- name: Create webdav, firmware folders
  file: path={{ item }} state=directory owner=www-data
  with_items:
  - /var/www/webdav
  - /var/www/webdav_temp
  - /var/www/firmware

- include: dehydrated.yml
- include: nginx-tls.yml
